#ifndef NOAH_SYSCALL_H
#define NOAH_SYSCALL_H

/*
 * The syscall table is arch-specific: aarch64 uses the generic numbering
 * (read=63, write=64, mmap=222 ...), unrelated to x86-64 (read=0, ...).
 * syscall_arm64.h is GENERATED by util/gen_syscall_table.py from the
 * kernel asm-generic/unistd.h; syscall_x86.h is the hand-kept x86 table.
 */
#ifdef __x86_64__
#include "syscall_x86.h"
#else
#include "syscall_arm64.h"
#endif

typedef uint64_t (*sc_handler_t)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);

extern sc_handler_t sc_handler_table[NR_SYSCALLS];
extern char *sc_name_table[NR_SYSCALLS];

#endif
