/*
 * aarch64 syscall table - GENERATED, do not edit by hand.
 * Regenerate: util/gen_syscall_table.py <unistd_generic.h>
 * See PORTING-arm64.md section 3.2.
 */
#include <stdint.h>

#define SYSCALLS \
  SYSCALL(0, unimplemented) \
  SYSCALL(1, unimplemented) \
  SYSCALL(2, unimplemented) \
  SYSCALL(3, unimplemented) \
  SYSCALL(4, unimplemented) \
  SYSCALL(5, setxattr) \
  SYSCALL(6, unimplemented) \
  SYSCALL(7, fsetxattr) \
  SYSCALL(8, getxattr) \
  SYSCALL(9, unimplemented) \
  SYSCALL(10, fgetxattr) \
  SYSCALL(11, unimplemented) \
  SYSCALL(12, unimplemented) \
  SYSCALL(13, flistxattr) \
  SYSCALL(14, unimplemented) \
  SYSCALL(15, unimplemented) \
  SYSCALL(16, unimplemented) \
  SYSCALL(17, getcwd) \
  SYSCALL(18, unimplemented) \
  SYSCALL(19, unimplemented) \
  SYSCALL(20, unimplemented) \
  SYSCALL(21, unimplemented) \
  SYSCALL(22, unimplemented) \
  SYSCALL(23, dup) \
  SYSCALL(24, dup3) \
  SYSCALL(25, fcntl) \
  SYSCALL(26, unimplemented) \
  SYSCALL(27, unimplemented) \
  SYSCALL(28, unimplemented) \
  SYSCALL(29, ioctl) \
  SYSCALL(30, unimplemented) \
  SYSCALL(31, unimplemented) \
  SYSCALL(32, flock) \
  SYSCALL(33, mknodat) \
  SYSCALL(34, mkdirat) \
  SYSCALL(35, unlinkat) \
  SYSCALL(36, symlinkat) \
  SYSCALL(37, linkat) \
  SYSCALL(38, renameat) \
  SYSCALL(39, unimplemented) \
  SYSCALL(40, unimplemented) \
  SYSCALL(41, unimplemented) \
  SYSCALL(42, nfsservctl) \
  SYSCALL(43, statfs) \
  SYSCALL(44, fstatfs) \
  SYSCALL(45, unimplemented) \
  SYSCALL(46, ftruncate) \
  SYSCALL(47, fallocate) \
  SYSCALL(48, faccessat) \
  SYSCALL(49, chdir) \
  SYSCALL(50, fchdir) \
  SYSCALL(51, chroot) \
  SYSCALL(52, fchmod) \
  SYSCALL(53, fchmodat) \
  SYSCALL(54, fchownat) \
  SYSCALL(55, fchown) \
  SYSCALL(56, openat) \
  SYSCALL(57, close) \
  SYSCALL(58, unimplemented) \
  SYSCALL(59, pipe2) \
  SYSCALL(60, unimplemented) \
  SYSCALL(61, getdents64) \
  SYSCALL(62, lseek) \
  SYSCALL(63, read) \
  SYSCALL(64, write) \
  SYSCALL(65, readv) \
  SYSCALL(66, writev) \
  SYSCALL(67, pread64) \
  SYSCALL(68, pwrite64) \
  SYSCALL(69, unimplemented) \
  SYSCALL(70, unimplemented) \
  SYSCALL(71, unimplemented) \
  SYSCALL(72, pselect6) \
  SYSCALL(73, unimplemented) \
  SYSCALL(74, unimplemented) \
  SYSCALL(75, unimplemented) \
  SYSCALL(76, unimplemented) \
  SYSCALL(77, unimplemented) \
  SYSCALL(78, readlinkat) \
  SYSCALL(79, newfstatat) \
  SYSCALL(80, fstat) \
  SYSCALL(81, sync) \
  SYSCALL(82, fsync) \
  SYSCALL(83, fdatasync) \
  SYSCALL(84, unimplemented) \
  SYSCALL(85, unimplemented) \
  SYSCALL(86, unimplemented) \
  SYSCALL(87, unimplemented) \
  SYSCALL(88, utimensat) \
  SYSCALL(89, unimplemented) \
  SYSCALL(90, capget) \
  SYSCALL(91, unimplemented) \
  SYSCALL(92, unimplemented) \
  SYSCALL(93, exit) \
  SYSCALL(94, exit_group) \
  SYSCALL(95, unimplemented) \
  SYSCALL(96, set_tid_address) \
  SYSCALL(97, unimplemented) \
  SYSCALL(98, futex) \
  SYSCALL(99, set_robust_list) \
  SYSCALL(100, unimplemented) \
  SYSCALL(101, nanosleep) \
  SYSCALL(102, getitimer) \
  SYSCALL(103, setitimer) \
  SYSCALL(104, unimplemented) \
  SYSCALL(105, unimplemented) \
  SYSCALL(106, unimplemented) \
  SYSCALL(107, unimplemented) \
  SYSCALL(108, unimplemented) \
  SYSCALL(109, unimplemented) \
  SYSCALL(110, unimplemented) \
  SYSCALL(111, unimplemented) \
  SYSCALL(112, unimplemented) \
  SYSCALL(113, clock_gettime) \
  SYSCALL(114, clock_getres) \
  SYSCALL(115, unimplemented) \
  SYSCALL(116, unimplemented) \
  SYSCALL(117, ptrace) \
  SYSCALL(118, unimplemented) \
  SYSCALL(119, unimplemented) \
  SYSCALL(120, unimplemented) \
  SYSCALL(121, unimplemented) \
  SYSCALL(122, unimplemented) \
  SYSCALL(123, sched_getaffinity) \
  SYSCALL(124, sched_yield) \
  SYSCALL(125, unimplemented) \
  SYSCALL(126, unimplemented) \
  SYSCALL(127, unimplemented) \
  SYSCALL(128, unimplemented) \
  SYSCALL(129, kill) \
  SYSCALL(130, unimplemented) \
  SYSCALL(131, tgkill) \
  SYSCALL(132, sigaltstack) \
  SYSCALL(133, rt_sigsuspend) \
  SYSCALL(134, rt_sigaction) \
  SYSCALL(135, rt_sigprocmask) \
  SYSCALL(136, rt_sigpending) \
  SYSCALL(137, unimplemented) \
  SYSCALL(138, unimplemented) \
  SYSCALL(139, rt_sigreturn) \
  SYSCALL(140, setpriority) \
  SYSCALL(141, getpriority) \
  SYSCALL(142, unimplemented) \
  SYSCALL(143, unimplemented) \
  SYSCALL(144, setgid) \
  SYSCALL(145, unimplemented) \
  SYSCALL(146, setuid) \
  SYSCALL(147, setresuid) \
  SYSCALL(148, getresuid) \
  SYSCALL(149, setresgid) \
  SYSCALL(150, getresgid) \
  SYSCALL(151, unimplemented) \
  SYSCALL(152, unimplemented) \
  SYSCALL(153, unimplemented) \
  SYSCALL(154, setpgid) \
  SYSCALL(155, getpgid) \
  SYSCALL(156, getsid) \
  SYSCALL(157, setsid) \
  SYSCALL(158, getgroups) \
  SYSCALL(159, setgroups) \
  SYSCALL(160, uname) \
  SYSCALL(161, unimplemented) \
  SYSCALL(162, unimplemented) \
  SYSCALL(163, getrlimit) \
  SYSCALL(164, setrlimit) \
  SYSCALL(165, getrusage) \
  SYSCALL(166, umask) \
  SYSCALL(167, prctl) \
  SYSCALL(168, unimplemented) \
  SYSCALL(169, gettimeofday) \
  SYSCALL(170, unimplemented) \
  SYSCALL(171, unimplemented) \
  SYSCALL(172, getpid) \
  SYSCALL(173, getppid) \
  SYSCALL(174, getuid) \
  SYSCALL(175, geteuid) \
  SYSCALL(176, getgid) \
  SYSCALL(177, getegid) \
  SYSCALL(178, gettid) \
  SYSCALL(179, sysinfo) \
  SYSCALL(180, unimplemented) \
  SYSCALL(181, unimplemented) \
  SYSCALL(182, unimplemented) \
  SYSCALL(183, unimplemented) \
  SYSCALL(184, unimplemented) \
  SYSCALL(185, unimplemented) \
  SYSCALL(186, unimplemented) \
  SYSCALL(187, unimplemented) \
  SYSCALL(188, unimplemented) \
  SYSCALL(189, unimplemented) \
  SYSCALL(190, semget) \
  SYSCALL(191, semctl) \
  SYSCALL(192, unimplemented) \
  SYSCALL(193, semop) \
  SYSCALL(194, shmget) \
  SYSCALL(195, shmctl) \
  SYSCALL(196, shmat) \
  SYSCALL(197, unimplemented) \
  SYSCALL(198, socket) \
  SYSCALL(199, socketpair) \
  SYSCALL(200, bind) \
  SYSCALL(201, listen) \
  SYSCALL(202, accept) \
  SYSCALL(203, connect) \
  SYSCALL(204, getsockname) \
  SYSCALL(205, getpeername) \
  SYSCALL(206, sendto) \
  SYSCALL(207, recvfrom) \
  SYSCALL(208, setsockopt) \
  SYSCALL(209, getsockopt) \
  SYSCALL(210, shutdown) \
  SYSCALL(211, sendmsg) \
  SYSCALL(212, recvmsg) \
  SYSCALL(213, unimplemented) \
  SYSCALL(214, brk) \
  SYSCALL(215, munmap) \
  SYSCALL(216, mremap) \
  SYSCALL(217, unimplemented) \
  SYSCALL(218, unimplemented) \
  SYSCALL(219, unimplemented) \
  SYSCALL(220, clone) \
  SYSCALL(221, execve) \
  SYSCALL(222, mmap) \
  SYSCALL(223, fadvise64) \
  SYSCALL(224, unimplemented) \
  SYSCALL(225, unimplemented) \
  SYSCALL(226, mprotect) \
  SYSCALL(227, msync) \
  SYSCALL(228, mlock) \
  SYSCALL(229, munlock) \
  SYSCALL(230, unimplemented) \
  SYSCALL(231, unimplemented) \
  SYSCALL(232, unimplemented) \
  SYSCALL(233, madvise) \
  SYSCALL(234, unimplemented) \
  SYSCALL(235, unimplemented) \
  SYSCALL(236, get_mempolicy) \
  SYSCALL(237, unimplemented) \
  SYSCALL(238, unimplemented) \
  SYSCALL(239, unimplemented) \
  SYSCALL(240, unimplemented) \
  SYSCALL(241, unimplemented) \
  SYSCALL(242, unimplemented) \
  SYSCALL(243, unimplemented) \
  SYSCALL(244, unimplemented) \
  SYSCALL(245, unimplemented) \
  SYSCALL(246, unimplemented) \
  SYSCALL(247, unimplemented) \
  SYSCALL(248, unimplemented) \
  SYSCALL(249, unimplemented) \
  SYSCALL(250, unimplemented) \
  SYSCALL(251, unimplemented) \
  SYSCALL(252, unimplemented) \
  SYSCALL(253, unimplemented) \
  SYSCALL(254, unimplemented) \
  SYSCALL(255, unimplemented) \
  SYSCALL(256, unimplemented) \
  SYSCALL(257, unimplemented) \
  SYSCALL(258, unimplemented) \
  SYSCALL(259, unimplemented) \
  SYSCALL(260, wait4) \
  SYSCALL(261, prlimit64) \
  SYSCALL(262, unimplemented) \
  SYSCALL(263, unimplemented) \
  SYSCALL(264, unimplemented) \
  SYSCALL(265, unimplemented) \
  SYSCALL(266, unimplemented) \
  SYSCALL(267, unimplemented) \
  SYSCALL(268, unimplemented) \
  SYSCALL(269, sendmmsg) \
  SYSCALL(270, unimplemented) \
  SYSCALL(271, unimplemented) \
  SYSCALL(272, unimplemented) \
  SYSCALL(273, unimplemented) \
  SYSCALL(274, unimplemented) \
  SYSCALL(275, unimplemented) \
  SYSCALL(276, unimplemented) \
  SYSCALL(277, unimplemented) \
  SYSCALL(278, getrandom) \
  SYSCALL(279, unimplemented) \
  SYSCALL(280, unimplemented) \
  SYSCALL(281, unimplemented) \
  SYSCALL(282, unimplemented) \
  SYSCALL(283, unimplemented) \
  SYSCALL(284, unimplemented) \
  SYSCALL(285, unimplemented) \
  SYSCALL(286, unimplemented) \
  SYSCALL(287, unimplemented) \
  SYSCALL(288, unimplemented) \
  SYSCALL(289, unimplemented) \
  SYSCALL(290, unimplemented) \
  SYSCALL(291, statx) \
  SYSCALL(292, unimplemented) \
  SYSCALL(293, unimplemented) \
  SYSCALL(294, unimplemented) \
  SYSCALL(295, unimplemented) \
  SYSCALL(296, unimplemented) \
  SYSCALL(297, unimplemented) \
  SYSCALL(298, unimplemented) \
  SYSCALL(299, unimplemented) \
  SYSCALL(300, unimplemented) \
  SYSCALL(301, unimplemented) \
  SYSCALL(302, unimplemented) \
  SYSCALL(303, unimplemented) \
  SYSCALL(304, unimplemented) \
  SYSCALL(305, unimplemented) \
  SYSCALL(306, unimplemented) \
  SYSCALL(307, unimplemented) \
  SYSCALL(308, unimplemented) \
  SYSCALL(309, unimplemented) \
  SYSCALL(310, unimplemented) \
  SYSCALL(311, unimplemented) \
  SYSCALL(312, unimplemented) \
  SYSCALL(313, unimplemented) \
  SYSCALL(314, unimplemented) \
  SYSCALL(315, unimplemented) \
  SYSCALL(316, unimplemented) \
  SYSCALL(317, unimplemented) \
  SYSCALL(318, unimplemented) \
  SYSCALL(319, unimplemented) \
  SYSCALL(320, unimplemented) \
  SYSCALL(321, unimplemented) \
  SYSCALL(322, unimplemented) \
  SYSCALL(323, unimplemented) \
  SYSCALL(324, unimplemented) \
  SYSCALL(325, unimplemented) \
  SYSCALL(326, unimplemented) \
  SYSCALL(327, unimplemented) \
  SYSCALL(328, unimplemented) \
  SYSCALL(329, unimplemented) \
  SYSCALL(330, unimplemented) \
  SYSCALL(331, unimplemented) \
  SYSCALL(332, unimplemented) \
  SYSCALL(333, unimplemented) \
  SYSCALL(334, unimplemented) \
  SYSCALL(335, unimplemented) \
  SYSCALL(336, unimplemented) \
  SYSCALL(337, unimplemented) \
  SYSCALL(338, unimplemented) \
  SYSCALL(339, unimplemented) \
  SYSCALL(340, unimplemented) \
  SYSCALL(341, unimplemented) \
  SYSCALL(342, unimplemented) \
  SYSCALL(343, unimplemented) \
  SYSCALL(344, unimplemented) \
  SYSCALL(345, unimplemented) \
  SYSCALL(346, unimplemented) \
  SYSCALL(347, unimplemented) \
  SYSCALL(348, unimplemented) \
  SYSCALL(349, unimplemented) \
  SYSCALL(350, unimplemented) \
  SYSCALL(351, unimplemented) \
  SYSCALL(352, unimplemented) \
  SYSCALL(353, unimplemented) \
  SYSCALL(354, unimplemented) \
  SYSCALL(355, unimplemented) \
  SYSCALL(356, unimplemented) \
  SYSCALL(357, unimplemented) \
  SYSCALL(358, unimplemented) \
  SYSCALL(359, unimplemented) \
  SYSCALL(360, unimplemented) \
  SYSCALL(361, unimplemented) \
  SYSCALL(362, unimplemented) \
  SYSCALL(363, unimplemented) \
  SYSCALL(364, unimplemented) \
  SYSCALL(365, unimplemented) \
  SYSCALL(366, unimplemented) \
  SYSCALL(367, unimplemented) \
  SYSCALL(368, unimplemented) \
  SYSCALL(369, unimplemented) \
  SYSCALL(370, unimplemented) \
  SYSCALL(371, unimplemented) \
  SYSCALL(372, unimplemented) \
  SYSCALL(373, unimplemented) \
  SYSCALL(374, unimplemented) \
  SYSCALL(375, unimplemented) \
  SYSCALL(376, unimplemented) \
  SYSCALL(377, unimplemented) \
  SYSCALL(378, unimplemented) \
  SYSCALL(379, unimplemented) \
  SYSCALL(380, unimplemented) \
  SYSCALL(381, unimplemented) \
  SYSCALL(382, unimplemented) \
  SYSCALL(383, unimplemented) \
  SYSCALL(384, unimplemented) \
  SYSCALL(385, unimplemented) \
  SYSCALL(386, unimplemented) \
  SYSCALL(387, unimplemented) \
  SYSCALL(388, unimplemented) \
  SYSCALL(389, unimplemented) \
  SYSCALL(390, unimplemented) \
  SYSCALL(391, unimplemented) \
  SYSCALL(392, unimplemented) \
  SYSCALL(393, unimplemented) \
  SYSCALL(394, unimplemented) \
  SYSCALL(395, unimplemented) \
  SYSCALL(396, unimplemented) \
  SYSCALL(397, unimplemented) \
  SYSCALL(398, unimplemented) \
  SYSCALL(399, unimplemented) \
  SYSCALL(400, unimplemented) \
  SYSCALL(401, unimplemented) \
  SYSCALL(402, unimplemented) \
  SYSCALL(403, unimplemented) \
  SYSCALL(404, unimplemented) \
  SYSCALL(405, unimplemented) \
  SYSCALL(406, unimplemented) \
  SYSCALL(407, unimplemented) \
  SYSCALL(408, unimplemented) \
  SYSCALL(409, unimplemented) \
  SYSCALL(410, unimplemented) \
  SYSCALL(411, unimplemented) \
  SYSCALL(412, unimplemented) \
  SYSCALL(413, unimplemented) \
  SYSCALL(414, unimplemented) \
  SYSCALL(415, unimplemented) \
  SYSCALL(416, unimplemented) \
  SYSCALL(417, unimplemented) \
  SYSCALL(418, unimplemented) \
  SYSCALL(419, unimplemented) \
  SYSCALL(420, unimplemented) \
  SYSCALL(421, unimplemented) \
  SYSCALL(422, unimplemented) \
  SYSCALL(423, unimplemented) \
  SYSCALL(424, unimplemented) \
  SYSCALL(425, unimplemented) \
  SYSCALL(426, unimplemented) \
  SYSCALL(427, unimplemented) \
  SYSCALL(428, unimplemented) \
  SYSCALL(429, unimplemented) \
  SYSCALL(430, unimplemented) \
  SYSCALL(431, unimplemented) \
  SYSCALL(432, unimplemented) \
  SYSCALL(433, unimplemented) \
  SYSCALL(434, unimplemented) \
  SYSCALL(435, unimplemented) \
  SYSCALL(436, unimplemented) \
  SYSCALL(437, unimplemented) \
  SYSCALL(438, unimplemented) \
  SYSCALL(439, unimplemented) \
  SYSCALL(440, unimplemented) \
  SYSCALL(441, unimplemented) \
  SYSCALL(442, unimplemented) \
  SYSCALL(443, unimplemented) \
  SYSCALL(444, unimplemented) \
  SYSCALL(445, unimplemented) \
  SYSCALL(446, unimplemented) \
  SYSCALL(447, unimplemented) \
  SYSCALL(448, unimplemented) \
  SYSCALL(449, unimplemented) \
  SYSCALL(450, unimplemented) \
  SYSCALL(451, unimplemented) \
  SYSCALL(452, unimplemented) \
  /* x86-legacy handlers with no aarch64 number - see the generator. */ \
  SYSCALL(453, access) \
  SYSCALL(454, afs_syscall) \
  SYSCALL(455, alarm) \
  SYSCALL(456, arch_prctl) \
  SYSCALL(457, chmod) \
  SYSCALL(458, chown) \
  SYSCALL(459, creat) \
  SYSCALL(460, dup2) \
  SYSCALL(461, epoll_ctl_old) \
  SYSCALL(462, epoll_wait_old) \
  SYSCALL(463, fork) \
  SYSCALL(464, get_thread_area) \
  SYSCALL(465, getdents) \
  SYSCALL(466, getpgrp) \
  SYSCALL(467, getpmsg) \
  SYSCALL(468, lchown) \
  SYSCALL(469, link) \
  SYSCALL(470, lstat) \
  SYSCALL(471, mkdir) \
  SYSCALL(472, mknod) \
  SYSCALL(473, open) \
  SYSCALL(474, pipe) \
  SYSCALL(475, poll) \
  SYSCALL(476, putpmsg) \
  SYSCALL(477, readlink) \
  SYSCALL(478, rename) \
  SYSCALL(479, rmdir) \
  SYSCALL(480, security) \
  SYSCALL(481, select) \
  SYSCALL(482, set_thread_area) \
  SYSCALL(483, stat) \
  SYSCALL(484, symlink) \
  SYSCALL(485, time) \
  SYSCALL(486, tuxcall) \
  SYSCALL(487, unlink) \
  SYSCALL(488, uselib) \
  SYSCALL(489, utime) \
  SYSCALL(490, utimes) \
  SYSCALL(491, vfork) \
  SYSCALL(492, vserver) \

#define NR_SYSCALLS 493
